DEF NUM_PLAYER_NAMES EQU 3

IF DEF(_RED)
DEF PLAYERNAME1 EQUS "RED"
DEF PLAYERNAME2 EQUS "ASH"
DEF PLAYERNAME3 EQUS "JACK"

DEF GIRLPLAYERNAME1 EQUS "GREEN"
DEF GIRLPLAYERNAME2 EQUS "MAY"
DEF GIRLPLAYERNAME3 EQUS "LEAF"

DEF RIVALNAME1 EQUS "BLUE"
DEF RIVALNAME2 EQUS "GARY"
DEF RIVALNAME3 EQUS "JOHN"
ENDC

IF DEF(_BLUE)
DEF PLAYERNAME1 EQUS "RED"
DEF PLAYERNAME2 EQUS "ASH"
DEF PLAYERNAME3 EQUS "JACK"

DEF GIRLPLAYERNAME1 EQUS "GREEN"
DEF GIRLPLAYERNAME2 EQUS "MAY"
DEF GIRLPLAYERNAME3 EQUS "LEAF"

DEF RIVALNAME1 EQUS "BLUE"
DEF RIVALNAME2 EQUS "GARY"
DEF RIVALNAME3 EQUS "JOHN"
ENDC
